apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-tezosconnect.fullname" . }}-config
  labels:
    {{- include "firefly-tezosconnect.labels" . | nindent 4 }}
stringData:
  config.yaml: |-
    {{- with .Values.config.confirmations }}
    confirmations:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.eventstreams }}
    eventstreams:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.webhooks }}
    webhooks:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.policyLoop }}
    policyloop:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.transactions }}
    transactions:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- tpl .Values.config.policyEngine . | nindent 4 }}

    log:
      level: {{ .Values.config.log.level | quote }}
      json:
        enabled: {{ .Values.config.log.jsonEnabled }}

    persistence:
      {{- if eq .Values.config.persistence.type "leveldb" }}
      type: leveldb
      leveldb:
        maxHandles: {{ .Values.config.persistence.leveldb.maxHandles | int }}
        path: /var/run/leveldb
        syncWrites: {{ .Values.config.persistence.leveldb.syncWrites }}
      {{- else if .Values.config.persistence.templateOverride }}
        {{ tpl .Values.config.persistence.templateOverride . | nindent 8 }}
      {{- end }}

    connector:
      blockchain:
        rpc: {{ .Values.config.connector.blockchain.rpc | quote }}
        network: {{ .Values.config.connector.blockchain.network | quote }}
        signatory: {{ .Values.config.connector.blockchain.signatory | quote }}
      

    api:
      port: {{ .Values.service.port }}
      address: 0.0.0.0
      publicURL: "http://{{ include "firefly-tezosconnect.fullname" . }}:{{ .Values.service.port }}"
