config:
  debugEnabled: true
  adminEnabled: true
  metricsEnabled: true
  preInit: true

  organizationName: "firefly-os"
  organizationKey: "tz1SfRoaCkrBkXqTzhz67QYVPJAU9Y2g48kq"
  fireflyContractAddress: ""

  tezosconnectUrl: "http://tezosconnect.firefly-os"

  postgresUrl: "postgres://postgres:firef1y@postgresql.default.svc:5432?sslmode=disable"
  postgresAutomigrate: true

  ipfsApiUrl: "http://ipfs.firefly-os:5001"
  ipfsGatewayUrl: "http://ipfs.firefly-os:8080"

  addresssResolverUrlTemplate: "http://address-resolver.firefly-os/wallets/{{.Key}}"

core:
  metrics:
    serviceMonitor:
      enabled: true

dataexchange:
  certificate:
    enabled: true
    issuerRef:
      kind: ClusterIssuer
      name: selfsigned-ca

  tlsSecret:
    enabled: false
